name: Check Changeset

on: pull_request

jobs:
  check_changeset:
    name: Check changeset vs changed files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Set up Node (10)
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Yarn install
      run: yarn
    - name: Run changeset script
      run: yarn ts-node-script scripts/check_changeset.ts
      id: check-changeset
    - name: Read output
      run: echo $MISSING_PACKAGES
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      id: couc
      with:
        issue-number: 1
        body: |
          Changeset warning: This PR modifies files in the following packages but they have not
          been included in the changeset file: ${{env.MISSING_PACKAGES}}